version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - ${PORT}
    # ports:
    #   - ${PORT}:${PORT}
    labels:
      caddy: ${DOMAIN}
      caddy.reverse_proxy: "{{upstreams ${PORT}}}"
