version: "3"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - ${PORT}
    # ports:
    #   - ${PORT}:${PORT}
    networks:
      - caddy
    labels:
      caddy: ${DOMAIN}
      caddy.reverse_proxy: "{{upstreams ${PORT}}}"

networks:
  caddy:
    external: true
