version: "3"
services:
  app:
    image: ghcr.io/gaolamthuy/gaolamthuy-api
    environment:
      - PORT=${PORT}
      -
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    networks:
      - caddy
    labels:
      caddy: ${DOMAIN_STAGING}
      caddy.reverse_proxy: "{{upstreams ${PORT}}}"

networks:
  caddy:
    external: true
